spring:
  # 配制数据库
  jdbc:
    datasource:
      driverClassName: com.mysql.jdbc.driver
      url: jdbc:mysql:///springboot
      username: root
      password: root
    #配置静态资源访问位置
  resources:
    static-locations:
      - classpath:/webapp
      - classpath:/static
# 应用服务 WEB 访问端口
server:
  port: 8080
