server:
  port: 10001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springboot
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis: # 配制redis
    host: 192.168.229.128
    port: 6379
druid:
  # 连接池的配置信息
  # 初始化大小，最小，最大
  initial-size: 5
  min-idle: 5
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
mybatis:
  type-aliases-package: com.atguigu.pojo
